// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollup/v1/l1blockinfo.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// L1BlockInfo represents information about an L1 block and associated L2 data.
type L1BlockInfo struct {
	Number            uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Time              uint64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	BaseFee           []byte `protobuf:"bytes,3,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	BlockHash         []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	SequenceNumber    uint64 `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	BatcherAddr       []byte `protobuf:"bytes,6,opt,name=batcher_addr,json=batcherAddr,proto3" json:"batcher_addr,omitempty"`
	L1FeeOverhead     []byte `protobuf:"bytes,7,opt,name=l1_fee_overhead,json=l1FeeOverhead,proto3" json:"l1_fee_overhead,omitempty"`
	L1FeeScalar       []byte `protobuf:"bytes,8,opt,name=l1_fee_scalar,json=l1FeeScalar,proto3" json:"l1_fee_scalar,omitempty"`
	BlobBaseFee       []byte `protobuf:"bytes,9,opt,name=blob_base_fee,json=blobBaseFee,proto3" json:"blob_base_fee,omitempty"`
	BaseFeeScalar     uint32 `protobuf:"varint,10,opt,name=base_fee_scalar,json=baseFeeScalar,proto3" json:"base_fee_scalar,omitempty"`
	BlobBaseFeeScalar uint32 `protobuf:"varint,11,opt,name=blob_base_fee_scalar,json=blobBaseFeeScalar,proto3" json:"blob_base_fee_scalar,omitempty"`
}

func (m *L1BlockInfo) Reset()         { *m = L1BlockInfo{} }
func (m *L1BlockInfo) String() string { return proto.CompactTextString(m) }
func (*L1BlockInfo) ProtoMessage()    {}
func (*L1BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3766382155f452ca, []int{0}
}
func (m *L1BlockInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *L1BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_L1BlockInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *L1BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L1BlockInfo.Merge(m, src)
}
func (m *L1BlockInfo) XXX_Size() int {
	return m.Size()
}
func (m *L1BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_L1BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_L1BlockInfo proto.InternalMessageInfo

func (m *L1BlockInfo) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *L1BlockInfo) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *L1BlockInfo) GetBaseFee() []byte {
	if m != nil {
		return m.BaseFee
	}
	return nil
}

func (m *L1BlockInfo) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *L1BlockInfo) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *L1BlockInfo) GetBatcherAddr() []byte {
	if m != nil {
		return m.BatcherAddr
	}
	return nil
}

func (m *L1BlockInfo) GetL1FeeOverhead() []byte {
	if m != nil {
		return m.L1FeeOverhead
	}
	return nil
}

func (m *L1BlockInfo) GetL1FeeScalar() []byte {
	if m != nil {
		return m.L1FeeScalar
	}
	return nil
}

func (m *L1BlockInfo) GetBlobBaseFee() []byte {
	if m != nil {
		return m.BlobBaseFee
	}
	return nil
}

func (m *L1BlockInfo) GetBaseFeeScalar() uint32 {
	if m != nil {
		return m.BaseFeeScalar
	}
	return 0
}

func (m *L1BlockInfo) GetBlobBaseFeeScalar() uint32 {
	if m != nil {
		return m.BlobBaseFeeScalar
	}
	return 0
}

func init() {
	proto.RegisterType((*L1BlockInfo)(nil), "rollup.v1.L1BlockInfo")
}

func init() { proto.RegisterFile("rollup/v1/l1blockinfo.proto", fileDescriptor_3766382155f452ca) }

var fileDescriptor_3766382155f452ca = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xc1, 0xae, 0x93, 0x40,
	0x14, 0x86, 0x3b, 0x5e, 0xec, 0x6d, 0x87, 0x62, 0xe3, 0xa4, 0x31, 0x44, 0x23, 0xad, 0x5d, 0x54,
	0x16, 0xa6, 0x13, 0xe2, 0x13, 0xc8, 0xa2, 0xd1, 0xc4, 0x68, 0x82, 0x3b, 0x37, 0x64, 0x06, 0x4e,
	0x4b, 0xe3, 0xc0, 0xe0, 0x00, 0x8d, 0x7d, 0x0b, 0x17, 0x3e, 0x54, 0x97, 0x5d, 0xba, 0x32, 0xa6,
	0x7d, 0x11, 0xc3, 0x30, 0x98, 0xde, 0xdd, 0xf0, 0xcd, 0x77, 0xfe, 0x73, 0x0e, 0x80, 0x5f, 0x28,
	0x29, 0x44, 0x53, 0xd2, 0x43, 0x40, 0x45, 0xc0, 0x85, 0x4c, 0xbe, 0xed, 0x8b, 0xad, 0x5c, 0x97,
	0x4a, 0xd6, 0x92, 0x8c, 0xbb, 0xcb, 0xf5, 0x21, 0x78, 0x3e, 0xdb, 0xc9, 0x9d, 0xd4, 0x94, 0xb6,
	0xa7, 0x4e, 0x58, 0xfe, 0xba, 0xc3, 0xf6, 0xc7, 0x20, 0x6c, 0xcb, 0x3e, 0x14, 0x5b, 0x49, 0x9e,
	0xe1, 0x61, 0xd1, 0xe4, 0x1c, 0x94, 0x8b, 0x16, 0xc8, 0xb7, 0x22, 0xf3, 0x44, 0x08, 0xb6, 0xea,
	0x7d, 0x0e, 0xee, 0x23, 0x4d, 0xf5, 0x99, 0xcc, 0xf1, 0x88, 0xb3, 0x0a, 0xe2, 0x2d, 0x80, 0x7b,
	0xb7, 0x40, 0xfe, 0x24, 0xb4, 0x4e, 0x7f, 0xe6, 0x28, 0xba, 0x6f, 0xe9, 0x06, 0x80, 0xbc, 0xc4,
	0x58, 0x0f, 0x14, 0x67, 0xac, 0xca, 0x5c, 0xab, 0x55, 0xa2, 0xb1, 0x26, 0xef, 0x59, 0x95, 0x91,
	0xd7, 0x78, 0x5a, 0xc1, 0xf7, 0x06, 0x8a, 0x04, 0x62, 0xd3, 0xf4, 0xb1, 0x8e, 0x7f, 0xd2, 0xe3,
	0x4f, 0x5d, 0xf3, 0x57, 0x78, 0xc2, 0x59, 0x9d, 0x64, 0xa0, 0x62, 0x96, 0xa6, 0xca, 0x1d, 0xea,
	0x24, 0xdb, 0xb0, 0x77, 0x69, 0xaa, 0xc8, 0x0a, 0x4f, 0x45, 0xd0, 0x4e, 0x12, 0xcb, 0x03, 0xa8,
	0x0c, 0x58, 0xea, 0xde, 0x6b, 0xcb, 0x11, 0xc1, 0x06, 0xe0, 0xb3, 0x81, 0x64, 0x89, 0x1d, 0xe3,
	0x55, 0x09, 0x13, 0x4c, 0xb9, 0xa3, 0x2e, 0x4b, 0x5b, 0x5f, 0x34, 0x22, 0x3e, 0x76, 0xb8, 0x90,
	0x3c, 0xfe, 0xbf, 0xdc, 0xf8, 0x66, 0x39, 0xbb, 0xbd, 0x0a, 0xcd, 0x82, 0x2b, 0x3c, 0xed, 0xa5,
	0x3e, 0x0f, 0x2f, 0x90, 0xef, 0x44, 0x8e, 0x79, 0x05, 0x26, 0x91, 0xe2, 0xd9, 0x83, 0xc4, 0x5e,
	0xb6, 0xb5, 0xfc, 0xf4, 0x26, 0xb2, 0x2b, 0x08, 0x37, 0xa7, 0x8b, 0x87, 0xce, 0x17, 0x0f, 0xfd,
	0xbd, 0x78, 0xe8, 0xe7, 0xd5, 0x1b, 0x9c, 0xaf, 0xde, 0xe0, 0xf7, 0xd5, 0x1b, 0x7c, 0x7d, 0xb3,
	0xdb, 0xd7, 0x59, 0xc3, 0xd7, 0x89, 0xcc, 0x69, 0x29, 0xc5, 0x31, 0x07, 0x95, 0x32, 0x49, 0x73,
	0x59, 0xc8, 0x1c, 0x14, 0xfd, 0x41, 0xcd, 0xef, 0x50, 0x1f, 0x4b, 0xa8, 0xf8, 0x50, 0x7f, 0xe5,
	0xb7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xaa, 0x0e, 0xd3, 0x25, 0x02, 0x00, 0x00,
}

func (m *L1BlockInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *L1BlockInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *L1BlockInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlobBaseFeeScalar != 0 {
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(m.BlobBaseFeeScalar))
		i--
		dAtA[i] = 0x58
	}
	if m.BaseFeeScalar != 0 {
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(m.BaseFeeScalar))
		i--
		dAtA[i] = 0x50
	}
	if len(m.BlobBaseFee) > 0 {
		i -= len(m.BlobBaseFee)
		copy(dAtA[i:], m.BlobBaseFee)
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(len(m.BlobBaseFee)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.L1FeeScalar) > 0 {
		i -= len(m.L1FeeScalar)
		copy(dAtA[i:], m.L1FeeScalar)
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(len(m.L1FeeScalar)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.L1FeeOverhead) > 0 {
		i -= len(m.L1FeeOverhead)
		copy(dAtA[i:], m.L1FeeOverhead)
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(len(m.L1FeeOverhead)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BatcherAddr) > 0 {
		i -= len(m.BatcherAddr)
		copy(dAtA[i:], m.BatcherAddr)
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(len(m.BatcherAddr)))
		i--
		dAtA[i] = 0x32
	}
	if m.SequenceNumber != 0 {
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(m.SequenceNumber))
		i--
		dAtA[i] = 0x28
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BaseFee) > 0 {
		i -= len(m.BaseFee)
		copy(dAtA[i:], m.BaseFee)
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(len(m.BaseFee)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Time != 0 {
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x10
	}
	if m.Number != 0 {
		i = encodeVarintL1Blockinfo(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintL1Blockinfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovL1Blockinfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *L1BlockInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 1 + sovL1Blockinfo(uint64(m.Number))
	}
	if m.Time != 0 {
		n += 1 + sovL1Blockinfo(uint64(m.Time))
	}
	l = len(m.BaseFee)
	if l > 0 {
		n += 1 + l + sovL1Blockinfo(uint64(l))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovL1Blockinfo(uint64(l))
	}
	if m.SequenceNumber != 0 {
		n += 1 + sovL1Blockinfo(uint64(m.SequenceNumber))
	}
	l = len(m.BatcherAddr)
	if l > 0 {
		n += 1 + l + sovL1Blockinfo(uint64(l))
	}
	l = len(m.L1FeeOverhead)
	if l > 0 {
		n += 1 + l + sovL1Blockinfo(uint64(l))
	}
	l = len(m.L1FeeScalar)
	if l > 0 {
		n += 1 + l + sovL1Blockinfo(uint64(l))
	}
	l = len(m.BlobBaseFee)
	if l > 0 {
		n += 1 + l + sovL1Blockinfo(uint64(l))
	}
	if m.BaseFeeScalar != 0 {
		n += 1 + sovL1Blockinfo(uint64(m.BaseFeeScalar))
	}
	if m.BlobBaseFeeScalar != 0 {
		n += 1 + sovL1Blockinfo(uint64(m.BlobBaseFeeScalar))
	}
	return n
}

func sovL1Blockinfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozL1Blockinfo(x uint64) (n int) {
	return sovL1Blockinfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *L1BlockInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowL1Blockinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: L1BlockInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: L1BlockInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseFee = append(m.BaseFee[:0], dAtA[iNdEx:postIndex]...)
			if m.BaseFee == nil {
				m.BaseFee = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = append(m.BlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockHash == nil {
				m.BlockHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceNumber", wireType)
			}
			m.SequenceNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SequenceNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatcherAddr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatcherAddr = append(m.BatcherAddr[:0], dAtA[iNdEx:postIndex]...)
			if m.BatcherAddr == nil {
				m.BatcherAddr = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1FeeOverhead", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1FeeOverhead = append(m.L1FeeOverhead[:0], dAtA[iNdEx:postIndex]...)
			if m.L1FeeOverhead == nil {
				m.L1FeeOverhead = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1FeeScalar", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1FeeScalar = append(m.L1FeeScalar[:0], dAtA[iNdEx:postIndex]...)
			if m.L1FeeScalar == nil {
				m.L1FeeScalar = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlobBaseFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlobBaseFee = append(m.BlobBaseFee[:0], dAtA[iNdEx:postIndex]...)
			if m.BlobBaseFee == nil {
				m.BlobBaseFee = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeeScalar", wireType)
			}
			m.BaseFeeScalar = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseFeeScalar |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlobBaseFeeScalar", wireType)
			}
			m.BlobBaseFeeScalar = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlobBaseFeeScalar |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipL1Blockinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthL1Blockinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipL1Blockinfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowL1Blockinfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowL1Blockinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthL1Blockinfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupL1Blockinfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthL1Blockinfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthL1Blockinfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowL1Blockinfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupL1Blockinfo = fmt.Errorf("proto: unexpected end of group")
)
