// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollup/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgApplyL1Txs defines the message for applying all L1 system and user deposit txs.
type MsgApplyL1Txs struct {
	// Array of bytes where each bytes is a eth.Transaction.MarshalBinary tx.
	// The first tx must be the L1 system deposit tx, and the rest are user txs if present.
	TxBytes [][]byte `protobuf:"bytes,1,rep,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	// The cosmos address of the L1 system and user deposit tx signer.
	FromAddress string `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
}

func (m *MsgApplyL1Txs) Reset()         { *m = MsgApplyL1Txs{} }
func (m *MsgApplyL1Txs) String() string { return proto.CompactTextString(m) }
func (*MsgApplyL1Txs) ProtoMessage()    {}
func (*MsgApplyL1Txs) Descriptor() ([]byte, []int) {
	return fileDescriptor_106533843870de0f, []int{0}
}
func (m *MsgApplyL1Txs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApplyL1Txs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApplyL1Txs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApplyL1Txs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApplyL1Txs.Merge(m, src)
}
func (m *MsgApplyL1Txs) XXX_Size() int {
	return m.Size()
}
func (m *MsgApplyL1Txs) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApplyL1Txs.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApplyL1Txs proto.InternalMessageInfo

func (m *MsgApplyL1Txs) GetTxBytes() [][]byte {
	if m != nil {
		return m.TxBytes
	}
	return nil
}

func (m *MsgApplyL1Txs) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

// MsgApplyL1TxsResponse defines the Msg/ApplyL1Txs response type.
type MsgApplyL1TxsResponse struct {
}

func (m *MsgApplyL1TxsResponse) Reset()         { *m = MsgApplyL1TxsResponse{} }
func (m *MsgApplyL1TxsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgApplyL1TxsResponse) ProtoMessage()    {}
func (*MsgApplyL1TxsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_106533843870de0f, []int{1}
}
func (m *MsgApplyL1TxsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApplyL1TxsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApplyL1TxsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApplyL1TxsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApplyL1TxsResponse.Merge(m, src)
}
func (m *MsgApplyL1TxsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgApplyL1TxsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApplyL1TxsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApplyL1TxsResponse proto.InternalMessageInfo

// MsgInitiateWithdrawal defines the message for initiating an L2 withdrawal.
type MsgInitiateWithdrawal struct {
	// The cosmos address of the user who wants to withdraw from L2.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// The ethereum address on L1 that the user wants to withdraw to.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// The amount of ETH (in wei) that the user wants to withdraw.
	Value cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=value,proto3,customtype=cosmossdk.io/math.Int" json:"value"`
	// Minimum gas limit for executing the message on L1.
	GasLimit []byte `protobuf:"bytes,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// Data to forward to L1 target.
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MsgInitiateWithdrawal) Reset()         { *m = MsgInitiateWithdrawal{} }
func (m *MsgInitiateWithdrawal) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateWithdrawal) ProtoMessage()    {}
func (*MsgInitiateWithdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_106533843870de0f, []int{2}
}
func (m *MsgInitiateWithdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiateWithdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiateWithdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiateWithdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateWithdrawal.Merge(m, src)
}
func (m *MsgInitiateWithdrawal) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiateWithdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateWithdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateWithdrawal proto.InternalMessageInfo

func (m *MsgInitiateWithdrawal) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgInitiateWithdrawal) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *MsgInitiateWithdrawal) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *MsgInitiateWithdrawal) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// MsgInitiateWithdrawalResponse defines the Msg/InitiateWithdrawal response type.
type MsgInitiateWithdrawalResponse struct {
}

func (m *MsgInitiateWithdrawalResponse) Reset()         { *m = MsgInitiateWithdrawalResponse{} }
func (m *MsgInitiateWithdrawalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateWithdrawalResponse) ProtoMessage()    {}
func (*MsgInitiateWithdrawalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_106533843870de0f, []int{3}
}
func (m *MsgInitiateWithdrawalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiateWithdrawalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiateWithdrawalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiateWithdrawalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateWithdrawalResponse.Merge(m, src)
}
func (m *MsgInitiateWithdrawalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiateWithdrawalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateWithdrawalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateWithdrawalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgApplyL1Txs)(nil), "rollup.v1.MsgApplyL1Txs")
	proto.RegisterType((*MsgApplyL1TxsResponse)(nil), "rollup.v1.MsgApplyL1TxsResponse")
	proto.RegisterType((*MsgInitiateWithdrawal)(nil), "rollup.v1.MsgInitiateWithdrawal")
	proto.RegisterType((*MsgInitiateWithdrawalResponse)(nil), "rollup.v1.MsgInitiateWithdrawalResponse")
}

func init() { proto.RegisterFile("rollup/v1/tx.proto", fileDescriptor_106533843870de0f) }

var fileDescriptor_106533843870de0f = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x31, 0x6f, 0x13, 0x31,
	0x14, 0x8e, 0x49, 0x1b, 0x1a, 0x37, 0x0c, 0xb5, 0x5a, 0x7a, 0x0d, 0xe2, 0x12, 0x32, 0x45, 0x15,
	0x3d, 0x37, 0xb0, 0x75, 0x6b, 0x86, 0x8a, 0x48, 0xed, 0x72, 0x20, 0x21, 0xb1, 0xa4, 0x4e, 0xcf,
	0x38, 0x27, 0xce, 0xe7, 0x93, 0xfd, 0x12, 0x92, 0x95, 0x5f, 0xc0, 0xcf, 0x60, 0x2c, 0x52, 0x7f,
	0x44, 0xc7, 0xaa, 0x13, 0x62, 0xa8, 0x50, 0x32, 0xe4, 0x6f, 0xa0, 0x3b, 0x3b, 0x88, 0x40, 0x11,
	0xcb, 0xc9, 0xdf, 0xf7, 0xbd, 0xf7, 0x3e, 0xfb, 0xbb, 0x87, 0x89, 0x56, 0x49, 0x32, 0xca, 0xe8,
	0xb8, 0x43, 0x61, 0x12, 0x64, 0x5a, 0x81, 0x22, 0x55, 0xcb, 0x05, 0xe3, 0x4e, 0x7d, 0x8b, 0xc9,
	0x38, 0x55, 0xb4, 0xf8, 0x5a, 0xb5, 0xbe, 0x7b, 0xa1, 0x8c, 0x54, 0x86, 0x4a, 0x23, 0xf2, 0x2e,
	0x69, 0x84, 0x13, 0xf6, 0xac, 0xd0, 0x2f, 0x10, 0xb5, 0xc0, 0x49, 0xdb, 0x42, 0x09, 0x65, 0xf9,
	0xfc, 0x64, 0xd9, 0xd6, 0x39, 0x7e, 0x74, 0x66, 0xc4, 0x71, 0x96, 0x25, 0xd3, 0xd3, 0xce, 0x9b,
	0x89, 0x21, 0x7b, 0x78, 0x03, 0x26, 0xfd, 0xc1, 0x14, 0xb8, 0xf1, 0x50, 0xb3, 0xdc, 0xae, 0x85,
	0x0f, 0x61, 0xd2, 0xcd, 0x21, 0x79, 0x86, 0x6b, 0xef, 0xb5, 0x92, 0x7d, 0x16, 0x45, 0x9a, 0x1b,
	0xe3, 0x3d, 0x68, 0xa2, 0x76, 0x35, 0xdc, 0xcc, 0xb9, 0x63, 0x4b, 0x1d, 0x6d, 0x7d, 0x5a, 0x5c,
	0xee, 0xaf, 0x54, 0xb5, 0x76, 0xf1, 0xce, 0x8a, 0x43, 0xc8, 0x4d, 0xa6, 0x52, 0xc3, 0x5b, 0x0b,
	0x54, 0x28, 0xbd, 0x34, 0x86, 0x98, 0x01, 0x7f, 0x1b, 0xc3, 0x30, 0xd2, 0xec, 0x23, 0x4b, 0xc8,
	0x21, 0xae, 0x18, 0x9e, 0x46, 0x5c, 0x7b, 0x28, 0xb7, 0xe8, 0x7a, 0xb7, 0x57, 0x07, 0xdb, 0xee,
	0x31, 0xce, 0xe9, 0x35, 0xe8, 0x38, 0x15, 0xa1, 0xab, 0x23, 0x8f, 0x71, 0x05, 0x98, 0x16, 0x1c,
	0xdc, 0xa5, 0x1c, 0x22, 0x27, 0x78, 0x7d, 0xcc, 0x92, 0x11, 0xf7, 0xca, 0xc5, 0xa0, 0xc3, 0xeb,
	0xbb, 0x46, 0xe9, 0xfb, 0x5d, 0x63, 0xc7, 0x0e, 0x33, 0xd1, 0x87, 0x20, 0x56, 0x54, 0x32, 0x18,
	0x06, 0xbd, 0x14, 0x6e, 0xaf, 0x0e, 0xb0, 0x73, 0xe9, 0xa5, 0xf0, 0x65, 0x71, 0xb9, 0x8f, 0x42,
	0xdb, 0x4e, 0x9e, 0xe0, 0xaa, 0x60, 0xa6, 0x9f, 0xc4, 0x32, 0x06, 0x6f, 0xad, 0x89, 0xda, 0xb5,
	0x70, 0x43, 0x30, 0x73, 0x9a, 0x63, 0x42, 0xf0, 0x5a, 0xc4, 0x80, 0x79, 0xeb, 0x05, 0x5f, 0x9c,
	0x8f, 0x36, 0xf3, 0x20, 0xdc, 0xed, 0x5a, 0x0d, 0xfc, 0xf4, 0xde, 0x87, 0x2e, 0xa3, 0x78, 0xf1,
	0x15, 0xe1, 0xf2, 0x99, 0x11, 0xe4, 0x15, 0xc6, 0xbf, 0xfd, 0x0a, 0x2f, 0xf8, 0xb5, 0x04, 0xc1,
	0x4a, 0x84, 0xf5, 0xe6, 0xbf, 0x94, 0xe5, 0x44, 0x72, 0x8e, 0xc9, 0x3d, 0xc1, 0xfe, 0xd1, 0xf7,
	0x77, 0x45, 0xbd, 0xfd, 0xbf, 0x8a, 0xa5, 0x43, 0xf7, 0xe4, 0x7a, 0xe6, 0xa3, 0x9b, 0x99, 0x8f,
	0x7e, 0xcc, 0x7c, 0xf4, 0x79, 0xee, 0x97, 0x6e, 0xe6, 0x7e, 0xe9, 0xdb, 0xdc, 0x2f, 0xbd, 0x7b,
	0x2e, 0x62, 0x18, 0x8e, 0x06, 0xc1, 0x85, 0x92, 0x34, 0x53, 0xc9, 0x54, 0x72, 0x1d, 0x31, 0x45,
	0xa5, 0x4a, 0x95, 0xe4, 0x9a, 0x4e, 0xa8, 0xdb, 0x77, 0x98, 0x66, 0xdc, 0x0c, 0x2a, 0xc5, 0x22,
	0xbe, 0xfc, 0x19, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x27, 0xf0, 0x02, 0x06, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ApplyL1Txs defines a method for applying applying all L1 system and user deposit txs.
	ApplyL1Txs(ctx context.Context, in *MsgApplyL1Txs, opts ...grpc.CallOption) (*MsgApplyL1TxsResponse, error)
	// InitiateWithdrawal defines a method for initiating a withdrawal from L2 to L1.
	InitiateWithdrawal(ctx context.Context, in *MsgInitiateWithdrawal, opts ...grpc.CallOption) (*MsgInitiateWithdrawalResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ApplyL1Txs(ctx context.Context, in *MsgApplyL1Txs, opts ...grpc.CallOption) (*MsgApplyL1TxsResponse, error) {
	out := new(MsgApplyL1TxsResponse)
	err := c.cc.Invoke(ctx, "/rollup.v1.Msg/ApplyL1Txs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitiateWithdrawal(ctx context.Context, in *MsgInitiateWithdrawal, opts ...grpc.CallOption) (*MsgInitiateWithdrawalResponse, error) {
	out := new(MsgInitiateWithdrawalResponse)
	err := c.cc.Invoke(ctx, "/rollup.v1.Msg/InitiateWithdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ApplyL1Txs defines a method for applying applying all L1 system and user deposit txs.
	ApplyL1Txs(context.Context, *MsgApplyL1Txs) (*MsgApplyL1TxsResponse, error)
	// InitiateWithdrawal defines a method for initiating a withdrawal from L2 to L1.
	InitiateWithdrawal(context.Context, *MsgInitiateWithdrawal) (*MsgInitiateWithdrawalResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ApplyL1Txs(ctx context.Context, req *MsgApplyL1Txs) (*MsgApplyL1TxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyL1Txs not implemented")
}
func (*UnimplementedMsgServer) InitiateWithdrawal(ctx context.Context, req *MsgInitiateWithdrawal) (*MsgInitiateWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateWithdrawal not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ApplyL1Txs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApplyL1Txs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApplyL1Txs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollup.v1.Msg/ApplyL1Txs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApplyL1Txs(ctx, req.(*MsgApplyL1Txs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitiateWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitiateWithdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitiateWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollup.v1.Msg/InitiateWithdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitiateWithdrawal(ctx, req.(*MsgInitiateWithdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rollup.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyL1Txs",
			Handler:    _Msg_ApplyL1Txs_Handler,
		},
		{
			MethodName: "InitiateWithdrawal",
			Handler:    _Msg_InitiateWithdrawal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollup/v1/tx.proto",
}

func (m *MsgApplyL1Txs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApplyL1Txs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApplyL1Txs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxBytes) > 0 {
		for iNdEx := len(m.TxBytes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TxBytes[iNdEx])
			copy(dAtA[i:], m.TxBytes[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.TxBytes[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MsgApplyL1TxsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApplyL1TxsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApplyL1TxsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgInitiateWithdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiateWithdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiateWithdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.GasLimit) > 0 {
		i -= len(m.GasLimit)
		copy(dAtA[i:], m.GasLimit)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GasLimit)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Target) > 0 {
		i -= len(m.Target)
		copy(dAtA[i:], m.Target)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Target)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitiateWithdrawalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiateWithdrawalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiateWithdrawalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgApplyL1Txs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TxBytes) > 0 {
		for _, b := range m.TxBytes {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgApplyL1TxsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgInitiateWithdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Value.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.GasLimit)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInitiateWithdrawalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgApplyL1Txs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApplyL1Txs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApplyL1Txs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxBytes = append(m.TxBytes, make([]byte, postIndex-iNdEx))
			copy(m.TxBytes[len(m.TxBytes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApplyL1TxsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApplyL1TxsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApplyL1TxsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitiateWithdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiateWithdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiateWithdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasLimit = append(m.GasLimit[:0], dAtA[iNdEx:postIndex]...)
			if m.GasLimit == nil {
				m.GasLimit = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitiateWithdrawalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiateWithdrawalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiateWithdrawalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
