_default:
    @just --list -f {{justfile()}}

HOME := "~/.pepctl"
r := "10"
s := "10"
u := "10"
f := "1"

# install pepctl
install:
    go install ./

# build pepctl for host OS
build:
    go build -o build/pepctl ./

# build pepctl for linux
build-linux:
    GOOS=linux GOARCH=amd64 go build -o build/pepctl ./

# inspect Peptide stores
inspect:
    go run ./ db inspect --home {{HOME}}

# Eg. just r=10 u=10 s=10 f=5 rollback
# rollback stores to a previous version with specified heights
rollback :
    go run ./ db rollback --home {{HOME}} --override -r {{r}} -s {{s}} -u {{u}} -f {{f}}
