name: docusaurus

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: doc/.nvmrc

      - name: Install dependencies
        working-directory: ./doc
        run: yarn install --frozen-lockfile

      - name: Build website
        working-directory: ./doc
        run: yarn build
