name: lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          # Required when using setup-go@v5, which enables caching by default.
          # https://github.com/golangci/golangci-lint-action/issues/677
          cache: false
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.2
